apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-creds
data:
  credentials: |
    [default]
    aws_access_key_id = AKIAUEVXKHGCKVWRNXII
    aws_secret_access_key = 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
