apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-creds
data:
  credentials: |
    [default]
    aws_access_key_id = AKIAYOMVXAWYQO5LGREE
    aws_secret_access_key = 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