# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci/cd for images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag reverseproxy touatiachraf/reverseproxy:v1
    - run: docker tag udagram-api-user touatiachraf/udagram-api-user:v1
    - run: docker tag udagram-api-feed touatiachraf/udagram-api-feed:v1
    - run: docker tag udagram-frontend:local touatiachraf/udagram-frontend:v1
    - run: echo "$DOCKER_PASSWORD". | docker login -u "$DOCKER_USERNAME" --password-stdin
    - run: docker push touatiachraf/reverseproxy:v1
    - run: docker push touatiachraf/udagram-api-feed:v1
    - run: docker push touatiachraf/udagram-api-user:v1
    - run: docker push touatiachraf/udagram-frontend:v1
 



